version: "3.9"

services:
  front:
    build: ./frontend
    volumes:
    - ./frontend:/app
    ports:
    - 3000:3000
  back:
    build: ./backend
    volumes:
    - ./backend:/appback
    ports:
    - 5000:5000
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example